### ISSUE TITLE
booting from USB results in "No working init found"

### ISSUE THREAD

**Issue by Jan1271** [finley/SystemImager#1]
Hi,
I am at the very beginning of using SystemImager and I am trying to clone an ubuntu 14.04.3 (3.19.0-28-generic #30~14.04.1-Ubuntu SMP) using systemimager 4.3.0. As stated in the manual first I ran `si_prepareclient --server <IP of image server> --include-system-firmware` on the client. The script ended with no errors saying that I am supposed to run `si_getimage` on the server now. 
That's what I did: `si_getimage -golden-client <IP of golden client> -image <name of image> -ip-assignment dhcp`. The script terminates without any errors. Subsequently, I wanted to create a bootable USB stick by running `si_mkautoinstalldisk --flavor <name of image> --device /dev/sdb`, also resulting in no error message. But when I put the stick in the machine (without any OS) during the booting I stuck with the message `end Kernel panic - not syncing: No working init found ....`. Have you experiences with this kind of error? Did I miss something while creating the image? Any advise how to proceed is highly appreciated. 

greetings

PS: I dont know if this important but the image server does not have the same kernel as the client (3.19.0-32-generic #37~14.04.1-Ubuntu SMP)

**Comment by stevegt** [comment]
Could be a few things, hard to give specific advice.  Check the console messages, ensure you're mounting the miniroot partition correctly, maybe mount the USB stick manually on a running machine and see if the filesystem looks sane and has an init.

What helps the most is the fact that systemimager is not actually magic -- other than the systemconfigurator bits (which I rarely use), it's basically just a conventional UNIX boot from removable media or network, followed by running the customizeable install script which formats the hard drive(s) and then runs rsync to pull down the image.  So forget trying to troubleshoot it as a systemimager problem, but instead troubleshoot boot issues as if it were any other UNIX.  Then go back and figure out where the systemimager scripts erred in creating the miniroot.

**Comment by olahaye74** [comment]
This error seems to be related to hardware detection (can't read usb filesystem or something related).
New SystemImager major rewrite I've done is based on dracut and shouldn't hit this kind of issue.
https://github.com/finley/SystemImager/wiki/QuickStartGuide
https://github.com/finley/SystemImager/tree/initrd-from-imageserver-and-dont-package-initrd
