### ISSUE TITLE
No index.html in /usr/share/systemimager/webgui/

### ISSUE THREAD

**Issue by Lotus907efi** [finley/SystemImager#14]
I have installed the latest systemimager pieces on Centos7-1908 and then tried following the directions from the Quick Start guide
However when I went to http://my_server_ip/ at first I got nothing back because the iptables rules would not permit access to port 80. Once I added the appropriate iptables rules, I got the default Centos test page ( Testing 123..
This page is used to test the proper operation of the Apache HTTP server )

So then I looked at the systemimager.conf file in /etc/httpd/conf.d/ and saw there was a directory alias for systemimager pointing to /usr/share/systemimager/webgui so I tried changing the URL in my browser to http://my_server_ip/systemimager but I got a permission error:

Forbidden
You don't have permission to access /systemimager/ on this server.

So I looked in the error_log in /var/log/httpd/ and it said:

[Sat Mar 07 17:32:04.596228 2020] [autoindex:error] [pid 10224] [client 192.168.121.50:50857] AH01276: Cannot serve directory /usr/share/systemimager/webgui/: No matching DirectoryIndex (index.html) found, and server-generated directory index forbidden by Options directive

and sure enough when I looked in the /usr/share/systemimager/webgui/ directory there was no index.html file present there. The only files there were:

total 96
-rw-r--r--. 1 root root 13397 Dec 19 13:20 client_console.php
-rw-r--r--. 1 root root  7571 Dec 19 13:20 client_list.php
drwxr-xr-x. 2 root root   117 Mar  7 17:04 css
-rw-r--r--. 1 root root  2850 Dec 19 13:20 edit_clusters.php
-rw-r--r--. 1 root root  7224 Dec 19 13:20 edit_config.php
-rw-r--r--. 1 root root  2845 Dec 19 13:20 edit_dhcp.php
-rw-r--r--. 1 root root  2312 Dec 19 13:20 functions.js
-rw-r--r--. 1 root root  6246 Dec 19 13:20 functions.php
-rw-r--r--. 1 root root  8360 Dec 19 13:20 health_console.php
drwxr-xr-x. 2 root root  4096 Mar  7 17:04 images
-rw-r--r--. 1 root root  3733 Dec 19 13:20 index.php
-rw-r--r--. 1 root root  2873 Dec 19 13:20 manage_netboot.php
-rw-r--r--. 1 root root  2578 Dec 19 13:20 push_client_defs.php
-rw-r--r--. 1 root root  5153 Dec 19 13:20 push_client_logs.php
-rw-r--r--. 1 root root   435 Dec 19 13:20 services.json
-rw-r--r--. 1 root root   266 Dec 19 13:20 statuses.json

When I tried using http://my_server_ip/systemimager/index.php or http://my_server_ip/systemimager/health_console.php I get web content but I am very certain it does NOT act as intended. I have attached a couple screenshots to show the results of this.
![systemimager_health_console_prob](https://user-images.githubusercontent.com/10698072/76153478-8e7ce000-609a-11ea-95dd-a016ac6fbf5f.jpg)
![systemimager_index_prob](https://user-images.githubusercontent.com/10698072/76153479-8fae0d00-609a-11ea-9898-88605a51dde7.jpg)

**Comment by Lotus907efi** [comment]
I am using Chrome running on a Linux desktop to view the systemimager webgui and in the /etc/httpd/conf.d/systemimager.conf file I have

Alias /systemimager /usr/share/systemimager/webgui
<Directory /usr/share/systemimager/webgui>
  AllowOverride All
  Require local
  # Require ip 10.0.1.1/24
  Require ip 192.168.121.1/24
</Directory>

but still when I go to http://oscartest1.mydomain.here/systemimager/ I still get the following error:

Forbidden
You don't have permission to access /systemimager/ on this server.

and in the  /var/log/httpd/error_log  file I see:

[Mon Mar 09 11:25:17.947965 2020] [autoindex:error] [pid 1754] [client 192.168.121.50:60965] AH01276: Cannot serve directory /usr/share/systemimager/webgui/: No matching DirectoryIndex (index.html) found, and server-generated directory index forbidden by Options directive

**Comment by mpex-lb** [comment]
> When I tried using http://my_server_ip/systemimager/index.php or http://my_server_ip/systemimager/health_console.php I get web content but I am very certain it does NOT act as intended. I have attached a couple screenshots to show the results of this.
> ![systemimager_health_console_prob](https://user-images.githubusercontent.com/10698072/76153478-8e7ce000-609a-11ea-95dd-a016ac6fbf5f.jpg)
> ![systemimager_index_prob](https://user-images.githubusercontent.com/10698072/76153479-8fae0d00-609a-11ea-9898-88605a51dde7.jpg)

The screenshots look like you didn't install php properly, as the php code is shown. The sections you highlight in green and red are just part of the php code, that needs to be executed by php. Please try to install php first, see this for example: https://www.howtoforge.com/tutorial/centos-lamp-server-apache-mysql-php/#-installing-php

> no matching DirectoryIndex (index.html) found,

As you don't have a index.html in your directory, the response is totally normal. You need to open the pages using there direct name like you did in your last try or define an alternative directory index by including this in your `<VirtualHost>` definition.
`DirectoryIndex index.php`

**Comment by Lotus907efi** [comment]
If php is a requirement, shouldn't that then be listed as a dependency for the systemimager-webgui package so it would get pulled in during the install process if it wasn't already installed?

**Comment by mpex-lb** [comment]
It should be automatically installed as a dependency, but your screenshots definitely look like you either don't have php installed or simply not enabled in your apache.
I'm using Debian, so I just remember basic CentOS/Redhat package management commands, you should be able to check if php is installed at all by using `rpm -q | grep php`. 
If you installed the systemimager packages manually and not through the package manager, that might explain any missing dependencies.

**Comment by Lotus907efi** [comment]
Ah HA!
I now have the systemimager configuration editor GUI running!

I did the following:

# yum install php
# yum --enablerepo=remi,remi-php71 install php-cli php-pear php-pdo php-mysqlnd php-gd php-mbstring php-mcrypt php-xml
and then I restarted httpd with

# systemctl restart httpd

Do you want me to add these steps to the systemimager quick start guide somewhere?

**Comment by Lotus907efi** [comment]
BTW, when I installed these packages the first time I did:

yum -y install systemimager-server dracut-systemimager systemimager-initrd_template systemimager-common systemimager-x86_64boot-standard systemimager-doc systemimager-client

During this step 80 other rpm dependencies did get pulled in but nothing about php.

When that did not work, I later went back and removed the packages with:

yum -y remove systemimager-server dracut-systemimager systemimager-initrd_template systemimager-common systemimager-x86_64boot-standard systemimager-doc systemimager-client

and then did a complete oscar install by doing:

yum install oscar

and 67 more dependent packages got pulled in but again nothing about php.

**Comment by Lotus907efi** [comment]
Also on CentOS-7.7 in order for the url http://my_server_IP/Systemimager/   to work instead of having to explicitly specify  http://my_server_IP/Systemimager/index.php

I had to make this change

`--- /etc/httpd/conf.d/systemimager.conf.rpmsave 2020-03-07 17:08:51.839848287 -0500
+++ /etc/httpd/conf.d/systemimager.conf 2020-03-09 14:52:51.895741668 -0400
@@ -6,6 +6,7 @@
 Alias /systemimager /usr/share/systemimager/webgui
 <Directory /usr/share/systemimager/webgui>
   AllowOverride All
+  DirectoryIndex index.html index.php
   Require local
   # Require ip 10.0.1.1/24
   Require ip 12.18.121.1/24`

Since the above keeps getting mangled I have attached the patch as a text file below

[systemimager.conf.patch.txt](https://github.com/finley/SystemImager/files/4308547/systemimager.conf.patch.txt)

**Comment by olahaye74** [comment]
Fixed by d0a5e79ee19d09218a5a58a61085487ddf89cb18 commit. php was not required by systemimager-webgui package.
installing php package and restarting http will fix the problem (php package will add index.php in Directory Index)
