### ISSUE TITLE
zero length file - /etc/systemimager/systemimager.json

### ISSUE THREAD

**Issue by Lotus907efi** [finley/SystemImager#15]
I installed the various systemimager bits from the oscar repo at http://www.usablesecurity.net/OSCAR/repos/unstable/rhel-7-x86_64/

and I have the following rpms:

systemimager-initrd_template-4.9.0-0.20191219git.el7.noarch
systemimager-server-4.9.0-0.20191219git.el7.noarch
systemimager-x86_64boot-standard-4.9.0-0.20191219git.el7.noarch
systemimager-webgui-4.9.0-0.20191219git.el7.noarch
dracut-systemimager-4.9.0-0.20191219git.el7.noarch
systemimager-doc-4.9.0-0.20191219git.el7.noarch
systemimager-common-4.9.0-0.20191219git.el7.noarch
systemimager-client-4.9.0-0.20191219git.el7.noarch

However when this was installed the file /etc/systemimager/systemimager.json was created but there is no content in the file. It is zero length:

-rw-r--r--. 1 apache root    0 Mar  7 17:04 /etc/systemimager/systemimager.json

I see there was a closed issue regarding this but I don't think it is really fixed yet.

BTW, when I did the install the following errors showed up during the install:

   1 malformed JSON string, neither array, object, number, string or atom, at character offset 0 (before "(end of string)") at /usr/share/perl5/vendor_perl/SystemImager/JConfig.pm line 179.
   2 Compilation failed in require at /usr/share/perl5/vendor_perl/SystemImager/Server.pm line 33.
   3 BEGIN failed--compilation aborted at /usr/share/perl5/vendor_perl/SystemImager/Server.pm line 33.
   4 Compilation failed in require at /usr/sbin/si_mkrsyncd_conf line 25.
   5 BEGIN failed--compilation aborted at /usr/sbin/si_mkrsyncd_conf line 25.
   6 WARNING: /usr/sbin/mkfs.jfs mot present. JFS support not available.
   7 WARNING: /usr/sbin/mkfs.reiserfs mot present. ReiserFS support not available.

so I am guessing the first error is in relation to this zero length systemimager.json file

**Comment by Lotus907efi** [comment]
BTW, the CentOS release is CentOS Linux release 7.7.1908

**Comment by Lotus907efi** [comment]
I also do not have a /usr/share/systemimager/webgui/config_scheme.json file present on the system either.

**Comment by Lotus907efi** [comment]
I tried doing the following:

yum -y remove systemimager-server dracut-systemimager systemimager-initrd_template systemimager-common systemimager-x86_64boot-standard systemimager-doc systemimager-client

and then installing all of oscar with 

yum install oscar

to see if pulling in all of the oscar stuff might fix this but I got the same set of errors during the install

  Installing : systemimager-webgui-4.9.0-0.20191219git.el7.noarch                                                              3/20 
WARNING: /usr/sbin/mkfs.jfs mot present. JFS support not available.
WARNING: /usr/sbin/mkfs.reiserfs mot present. ReiserFS support not available.
  Installing : dracut-systemimager-4.9.0-0.20191219git.el7.noarch                                                              4/20 
  Installing : systemimager-common-4.9.0-0.20191219git.el7.noarch                                                              5/20 
  Installing : systemimager-server-4.9.0-0.20191219git.el7.noarch                                                              6/20 
malformed JSON string, neither array, object, number, string or atom, at character offset 0 (before "(end of string)") at /usr/share/perl5/vendor_perl/SystemImager/JConfig.pm line 179.
Compilation failed in require at /usr/share/perl5/vendor_perl/SystemImager/Server.pm line 33.
BEGIN failed--compilation aborted at /usr/share/perl5/vendor_perl/SystemImager/Server.pm line 33.
Compilation failed in require at /usr/sbin/si_mkrsyncd_conf line 25.
BEGIN failed--compilation aborted at /usr/sbin/si_mkrsyncd_conf line 25.

**Comment by Lotus907efi** [comment]
Should I try touching the file /etc/systemimager/systemimager.json prior to doing the install to see if that makes any difference?

**Comment by olahaye74** [comment]
Problem identified.
- I need to add php-json as a systemimager-webgui dependency
- The json file is empty because is is filled by webgui using default values found in the scheme file. Bad script design, it should use th scheme file to generate the default file.
- The scheme file seems not packaged: investigating

**Comment by olahaye74** [comment]
Fixed by 8287b502ef5cc378ce6ab4b36fbb529c24b47b20 and c52d44067b4f1a935cf16484a5de74574a805efb
