### ISSUE TITLE
Missing si_monitord in systemimager.spec

### ISSUE THREAD

**Issue by theasp** [finley/SystemImager#16]
Hi,

I'm trying to use the oscar RPMs of SystemImage pre-v5, which look like they are built from the spec file in the repo.  It looks like the spec file is missing the line to put si_monitord into the server package.  I could do a PR if you'd like, but is anything else missing?  Am I wrong?

**Comment by theasp** [comment]
After a bit of playing around, I think it is missing on purpose, as it's not installed by the makefile either.  Feel free to close if this is the case.

**Comment by olahaye74** [comment]
Yes, si_monitord is obsoleted in the Next Generation web based version.
