### ISSUE TITLE
Unimplemented: POSIX::tmpnam(): use File::Temp instead at /usr/sbin/si_prepareclient line 98.

### ISSUE THREAD

**Issue by jarivai** [finley/SystemImager#18]
The tmpnam() seems to cause problems on Debian 9 based system running with i386 compatibility libraries...

**Comment by nbtm-sh** [comment]
I fixed this issue by changing the line

```perl
use File::Temp qw/ :POSIX /;
```

to `/usr/sbin/si_prepareclient`

You may also need to do this to the other files. I'm planning to fork this repo in the future to make it work on modern versions of Debian

**Comment by olahaye74** [comment]
Issue fixed in recent build with the following line:
use File::Temp qw/ mktemp /;

Please don't fork, instead you're welcome to participate and help the projet. I'm looking forward for a skilled Debian packager.
Cheers

**Comment by olahaye74** [comment]
Merged pull request and added templates for filenames.
