### ISSUE TITLE
Ubuntu Desktop 18.04 

### ISSUE THREAD

**Issue by lyndonlu** [finley/SystemImager#19]
Hi,

    Can the Ubuntu Desktop 18.04 be imaged with SystemImager? Thanks.

-Lyndon

**Comment by olahaye74** [comment]
I'd like to build deb package, but I still have a lot of work on it. I need to review the full packaging and I need to check that dracut is now functional and not conflicting with initramfstools.
My priority is to make a stable release 1st for RHEL based distress then re-create the deb packaging.
Keeping open until I fix this.

**Comment by olahaye74** [comment]
I've built package for Debian 10 and 11:
http://olivier.lahaye1.free.fr/OSCAR/repos/unstable/debian-10-x86_64/
http://olivier.lahaye1.free.fr/OSCAR/repos/unstable/debian-11-x86_64/

**Comment by olahaye74** [comment]
Ubuntu-18.04 should accept Debian-10 packages.
Closing issue.
