### ISSUE TITLE
si_prepareclient fails with message Undefined subroutine &main::mktemp called at /usr/sbin/si_prepareclient line 93

### ISSUE THREAD

**Issue by heinzhauck** [finley/SystemImager#20]
I started si_prepareclient (4.9.0-0.20201009git.el7) with the folloing options:

# si_prepareclient --server grzulicl1-hn1 --no-uyok -yes
Undefined subroutine &main::mktemp called at /usr/sbin/si_prepareclient line 93.

Then i changed the use line File::Temp:

#use File::Temp qw/ tempfile tempdir /;
use File::Temp;

and it worked:

# si_prepareclient --server grzulicl1-hn1 --no-uyok -yes
Subroutine main::tmpnam redefined at /usr/share/perl5/vendor_perl/Exporter.pm line 66.
 at /usr/sbin/si_prepareclient line 78.
Using "parted" to gather information about disk:
    /dev/sda

Starting or re-starting rsync as a daemon.....
done!

This client is ready to have its image retrieved.  You must now run 
the "si_getimage" command on your imageserver.

Automatically create configuration file for systemconfigurator:
  >> /etc/systemconfig/systemconfig.conf

**Comment by olahaye74** [comment]
Thanks for notice, It was fixed later by using:
use File::Temp qw/ mktemp /;

New build available.
