### ISSUE TITLE
Unable to download SystemImager - Error 403 Forbidden

### ISSUE THREAD

**Issue by magspad** [finley/SystemImager#21]
Hi,

When I try to download and install SystemImager (on a RHEL 8.3 system) I get the following error during 'dnf install systemimager-server':

Errors during downloading metadata for repository 'systemimager-stable':
  - Status code: 403 for https://dl.bintray.com/systemimager/rpms/el8/x86_64/repodata/repomd.xml (IP: 50.112.35.45)
Error: Failed to download metadata for repo  'systemimager-stable': Cannot download repomd.xml: All mirrors were tried

And when I go to that URL (https://dl.bintray.com/systemimager/rpms/el8/x86_64/repodata/repomd.xml) in a browser, I get the error:
Forbidden!

Please help.

Thanks,
Mag

**Comment by olahaye74** [comment]
Please follow the quick start guide:
https://github.com/finley/SystemImager/wiki/QuickStartGuide
Cheers
