### ISSUE TITLE
Linux distros compatibility

### ISSUE THREAD

**Issue by sramirez** [finley/SystemImager#3]
Hi,

We're just wondering if the current version of SystemImager is valid for CentOS 7. We try  to replicate a CentOS 7 image with the SourceForge version without sucess. Since CentOS 7 has supposed a big change with respect to the previous version, I supposed that it is not adapted for these new Linux versions. Is it true?

Thanks in advance.

**Comment by olahaye74** [comment]
CentOS-7 supported (aside CentOS-6, SuSE-42.x, Fedora-27+)
See https://github.com/finley/SystemImager/wiki/QuickStartGuide
