### ISSUE TITLE
jfsutils-1.1.15 - upgrade to a newer version of provide a patch for this version within the make process

### ISSUE THREAD

**Issue by metalcated** [finley/SystemImager#5]
sed "s@<unistd.h>@&\n#include <sys/types.h>@g" -i initrd_source/src# jfsutils-1.1.14/fscklog/extract.c 

source: http://archives.linuxfromscratch.org/mail-archives/blfs-support/2013-March/072202.html

**Comment by olahaye74** [comment]
systemimager now use host binaries and dracut to build initrd.img.
Installing jfs utils from host linux distro repositories fixes the problem.
need v4.9.0 at least.
