### ISSUE TITLE
rsync extended attributes flag

### ISSUE THREAD

**Issue by stevegt** [finley/SystemImager#6]
(Hi Brian!)

I'm the guy who contributed the `-HS` rsync flags patch to systemimager in 2003 (https://github.com/finley/SystemImager/commit/ffe0826c641d18b86aa69b347093af7c297c1c81).  

The `-X` flag ought to be added as well, so extended attributes get copied.  Here's one place that would need be done:

https://github.com/finley/SystemImager/blob/afc50d15bb5dfd893c33e85517c05fafdd0e3c57/sbin/si_getimage#L449

I sorta have an excuse for missing this in 2003: rsync didn't support `-X` until 2008.   :stuck_out_tongue: 

https://download.samba.org/pub/rsync/src/rsync-3.0.0-NEWS

**Comment by heinzhauck** [comment]
Hello Brian
I have the same problem with extended file attributes (file capabilities of rsh/rcp/rlogin).
Could you please add the rsync options -X (extended Attributes) and -A (Access Control Lists) to the rsync options of si_getimage, si_updateclient, si_pcp, systemimager-xmit-rsync.sh and systemimager-xmit-flamethrower.sh.

**Comment by heinzhauck** [comment]
Hello Brian
Please ignore my comment, i tried to update an Image with si_getimage to a NetApp NFS Storage and got Errors (rsync: rsync_xal_set: lsetxattr failed: Operation not supported (95)), and the same error when installing the Image on Client.
Ist better to restore file capabilities with the post-install script!

**Comment by olahaye74** [comment]
Hello Heinz,

New systemimager (Major rewrite I've done) is using dracut and is now able to image without any script (though they are still available). Systemimager is able to initialise storage from a disk-layout.xml file  deploy the image, install bootloader (either legacy or efi) and configure network (most common usages (ethernet, bonding, infiniband, ...).
This version is in branch  initrd-from-imageserver-and-dont-package-initrd 
See https://github.com/finley/SystemImager/wiki/QuickStartGuide

If you want to contribute, you can join systemimager.slack.com.
The correct development branch is https://github.com/finley/SystemImager/tree/initrd-from-imageserver-and-dont-package-initrd

**Comment by heinzhauck** [comment]
Thank you for information!


  Mit freundlichen Grüßen:
       (best regards)

Heinz Hauck

Senior System Engineer
IT Infrastructure Systems
MAGNA STEYR IT

MAGNA STEYR Fahrzeugtechnik AG & Co KG
Liebenauer Hauptstrasse 317, 8041 Graz, Austria
Phone:              +43 (0) 316 404 3455
Fax:                   +43 (0) 316 404 6400
Email:                 heinz.hauck@magna.com<mailto:heinz.hauck@magna.com>
Homepage:        www.magna.com<http://www.magna.com/>
____________________________________________________________________________________
Diese Nachricht ist fuer die MAGNA STEYR Fahrzeugtechnik AG & Co KG rechtsunverbindlich!
This message is not legally binding upon MAGNA STEYR Fahrzeugtechnik AG & Co KG!_______

Von: Olivier LAHAYE [mailto:notifications@github.com]
Gesendet: Montag, 22. April 2019 11:19
An: finley/SystemImager <SystemImager@noreply.github.com>
Cc: Hauck Heinz (IGB, MSF) <heinz.hauck@magna.com>; Comment <comment@noreply.github.com>
Betreff: Re: [finley/SystemImager] rsync extended attributes flag (#6)


New systemimager (Major rewrite I've done) is using dracut and is now able to image without any script (though they are still available). Systemimager is able to initialise storage from a disk-layout.xml file deploy the image, install bootloader (either legacy or efi) and configure network (most common usages (ethernet, bonding, infiniband, ...).
This version is in branch initrd-from-imageserver-and-dont-package-initrd
See https://github.com/finley/SystemImager/wiki/QuickStartGuide

**Comment by olahaye74** [comment]
New progress:
- New WebGUI (realtime web console, config editor and more)
- New config based on JSON format for all systemimager components.

Closing this bug as it is not relevant for current development version and stable release does not build anymore.
