### ISSUE TITLE
Support for LABEL=swap

### ISSUE THREAD

**Issue by heinzhauck** [finley/SystemImager#8]
Hello Brian

Could you please add support for swap partition definition LABEL=swap in /etc/fstab.
If i define the swap partition like this:
\<fsinfo  line="60" real_dev="/dev/sda2" mount_dev="LABEL=swap2"      mp="swap"     fs="swap" options="defaults" dump="0" pass="0" />

The swap file should be created with the following command:
mkswap -v1  -L swap /dev/sda2

Thank you in advance
Heinz Hauck

**Comment by olahaye74** [comment]
Hi Heinz, if I'm correct, it is supported in branch  initrd-from-imageserver-and-dont-package-initrd which is the branch that will soon go to master (I'm the developper of this major rewrite based on dracut).

please join systemimager.slack.com (very active there; reply are faster)

**Comment by olahaye74** [comment]
diskmgt-lib.sh line 1024 in  initrd-from-imageserver-and-dont-package-initrd supports this syntax: LABEL= for swap partitions.
