### ISSUE TITLE
Corrections in /usr/lib/dracut/modules.d/51systemimager/module-setup.sh

### ISSUE THREAD

**Issue by heinzhauck** [finley/SystemImager#9]
Hello Brian

I corrected two Errors in module-setup.sh:

       line 36:
                message: /usr/lib/dracut/modules.d/51systemimager/module-setup.sh: line 36: cd: /usr/share/systemimager/boot/x86_64/standard/initrd_template/: No such file or directory
                before: cd ${SI_INITRD_TEMPLATE:=/usr/share/systemimager/boot/$(uname -m)/standard/initrd_template/};
                after:  cd ${SI_INITRD_TEMPLATE:=/usr/share/systemimager/boot/initrd_template/};

        line 124:
                message: tar: This does not look like a tar archive; tar: Exiting with failure status due to previous errors
                before: (cd /etc; test -f docker/seccomp.json && tar cpf - docker/seccomp.json)|(cd $initdir/etc; tar xpf -)
                after:  test -f /etc/docker/seccomp.json && (cd /etc; tar cpf - docker/seccomp.json)|(cd $initdir/etc; tar xpf -)

**Comment by olahaye74** [comment]
Thanks for reporting and fix.
I've fixed it in 20190705 build.

PS: I'm the dracut module developper and main SystemImager developper now :-)
